if (!isServer) exitWith {};
 
waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};

[ALIVE_factionDefaultAirTransport, "unsung_w", ["uns_hh53b_m134_usaf"]] call ALIVE_fnc_hashSet;

ALiVE_PLACEMENT_CUSTOM_UNITBLACKLIST = [];
ALiVE_MIL_CQB_CUSTOM_UNITBLACKLIST = ALiVE_PLACEMENT_CUSTOM_UNITBLACKLIST;
ALIVE_autoGeneratedTasks = [];
